server:
  port: 8989
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#springcloud config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2238036648a/demoConfig.git